name: First

on: push



jobs:
  job1:
    name:first job
    build:
      name:first build
    runs-on: windows-2019
    steps:
      - name:step1
      - uses: actions/checkout@v3
      - run: ./gradlew test