name: First

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test


      - name: build project
      run: ./gradle assemble