name: Android Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK              // 1
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions  // 2
        run: chmod +x ./gradlew

          #      - name: Run Tests                   // 3
          #        run: ./gradlew test
          #
          #      - name: Build Project               // 4
          #        run: ./gradlew assemble

          #      - name: Build Debug Apk
          #        run: ./gradlew assembleDebug


          # job of sending mail by gmail
          #      - name: send email
          #        uses: dawidd6/action-send-mail@v3.6.1
          #        with:
          #          server_address: smtp.gmail.com
          #          server_port: 465
          #          username: ${{secrets.MAIL_USER_NAME}}
          #          # Optional (recommended) mail server password:
          #          password: ${{secrets.MAIL_PASSWORD}}
          #          # Required mail subject:
          #          subject: Github Actions job result
          #          # Required recipients' addresses:
          #          to: eslamsaad45@gmail.com
          #          # Required sender full name (address can be skipped):
          #          from: Luke Skywalker # <user@example.com>
          #          # Optional whether this connection use TLS (default is true if server_port is 465)
          #          secure: true
        #          # Optional plain body:
        #          body: Build job of
        #          attachments: app/build/outputs/apk/debug/app-debug.apk

      - name: Trust GitHub workspace
        run:
          git config --global --add safe.directory /github/workspace
        #Upload Apk to Firebase Distribution
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: app/build/outputs/apk/debug/app-debug.apk





